# Generated by Django 3.0.5 on 2020-04-29 23:31

from django.db import migrations
import csv

def parse_csv(apps, schema_editor):
    Symptom = apps.get_model("api", "Symptom")
    Condition  = apps.get_model("api", "Condition")
    Diagnosis = apps.get_model("api", "Diagnosis")

    with open('symptoms.csv') as csv_file:
        reader = csv.reader(csv_file)

        for row in reader:
            symptom = Symptom.objects.create(name=row.pop(0))
            for conditionName in row:
                condition = Condition.objects.create(name=conditionName)
                diagnosis = Diagnosis(condition=condition, symptom=symptom)
                diagnosis.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(parse_csv)
    ]
